Eczane.WebUI/Areas/Admin/Controllers/EczaciKalfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Web;
using System.Web.Mvc;
using Eczane.BL.Manage;
using Eczane.WebUI.Models;
using Microsoft.AspNet.Identity;

namespace Eczane.WebUI.Areas.Admin.Controllers
{
    public class EczaciKalfaController : Controller
    {
        private readonly EczaneDbContext ctx;
        public EczaciKalfaController()
        {
            ctx=new EczaneDbContext();
        }
        // GET: Admin/EczaciKalfa
        public ActionResult Index()
        {          
            var Istek = ctx.IstekBilgileri.Include("Eczaci").Include("KalfaEczaci").Include("Eczaci.User").Include("KalfaEczaci.User").Select(x=> new EczaciKalfaIstekDTO()
            {
                Id=x.Id,
                EczaciAdi = x.Eczaci.Kisi.Ad,
                EczaciSoyAdi = x.Eczaci.Kisi.SoyAd,
                Email = x.Eczaci.User.Email,
                Tel = x.Eczaci.Kisi.Telefon,
                KalfaEczaciAdi = x.KalfaEczaci.Kisi.Ad,
                KalfaEczaciSoyAdi = x.KalfaEczaci.Kisi.SoyAd,
                KalfaEmail = x.KalfaEczaci.User.Email,
                KalfaTel = x.KalfaEczaci.Kisi.Telefon,
                IstekGonderildiMi = x.IstekGonderildiMi,
                IstekGonderilmeTarihi =  x.IstekGonderilmeTarihi,
                AdminIstekOnayTarihi =  x.AdminIstekOnayTarihi
            } ).ToList();
            foreach (var item in Istek)
            {
               item.IstekGonderilmeTarihistr= String.Format("{0:d}", item.IstekGonderilmeTarihi);
                item.AdminIstekOnayTarihistr = String.Format("{0:d}", item.AdminIstekOnayTarihi);
            }
            return View(Istek);
        }
        //TODO Admin Onaylayacak Kısmı Yapılcak
        public JsonResult IstekYap(int id)
        {
            try
            {
                var result = ctx.IstekBilgileri.FirstOrDefault(x => x.Id == id);
                result.AdminIstekOnayTarihi=DateTime.Now;
                result.IstekGonderildiMi = true;
                ctx.SaveChanges();
                return Json("İşlem Başarılı",JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(e.Message); 
            }
        }
    }
}

Eczane.WebUI/Areas/Admin/Views/EczaciKalfa/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage.cshtml";
}
@model List<Eczane.WebUI.Models.EczaciKalfaIstekDTO>
<div class="row">
    <div class="col-md-6">
        <h1 class="page-header">
            Eczaci Kalfa  <small>İstekler</small>
        </h1>
    </div>
</div>
<div class="row">
    <div clas="col-md-12">
        <div class="row col-md-6">
            <div class="panel-body">
                <div class="table-responsive">
                    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" aria-describedby="dataTables-example_info">
                            <thead>
                            <tr role="row">
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Eczaci Adı</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Eczaci SoyAdı</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Telefon Bilgisi</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Email Bilgisi</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Kalfa Eczaci Adı</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Kalfa Eczaci SoyAdı</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Kalfa Telefon Bilgisi</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Kalfa Email Bilgisi</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Admin IstekOnay Tarihi</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Istek Gonderilme Tarihi</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Istek Gonderildi Mi</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Istek Gönderildi İşlemi</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.EczaciAdi</td>
                                    <td>@item.EczaciSoyAdi</td>
                                    <td>@item.Tel</td>
                                    <td>@item.Email</td>
                                    <td>@item.KalfaEczaciAdi</td>
                                    <td>@item.KalfaEczaciSoyAdi</td>
                                    <td>@item.KalfaTel</td>
                                    <td>@item.KalfaEmail</td>
                                    <td>@item.AdminIstekOnayTarihi</td>
                                    <td>@item.IstekGonderilmeTarihi</td>
                                    <td>@{
                                            var sonuc= item.IstekGonderildiMi == true ?  "Evet" :  "Hayır";
                                            @sonuc;
                                        }</td>
                                    <td onclick="IstekYapildi(@item.Id)"><i class="fa fa-refresh"></i></td>
                                </tr>                                  
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade in" id="myModalMesaj" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabelMesaj">Bilgi Mesajı</h4>
            </div>
            <div class="modal-body">
                <strong id="modalMesajMesaj">

                </strong>
            </div>
            <div class="modal-footer">
                <button id="close" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<script>
    function IstekYapildi(id) {
        $.ajax({
            url: '@Url.Action("IstekYap","EczaciKalfa",new {Area="Admin"})',
            data: { id: id},
            success: function (data) {
                $("#modalMesajMesaj").text(data);
                $("#myModalMesaj").modal("show");
            },
            type: 'GET',
            dataType: 'json'
        });
    }
    $("#close").on("click", function () {
        if (sonuc = "Kayıt Başarılı") {
            location.reload();
        }
    });
</script>