Eczane.WebUI/Areas/KalfaEczaci/Controllers/KalfaEczaciIslemController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Eczane.BL.Entities;
using Eczane.BL.Helpers;
using Eczane.BL.Manage;
using Microsoft.AspNet.Identity;

namespace Eczane.WebUI.Areas.KalfaEczaci.Controllers
{
    public class KalfaEczaciIslemController : Controller
    {
        private readonly EczaneDbContext ctx;
        public KalfaEczaciIslemController()
        {
            ctx=new EczaneDbContext();
        }
        // GET: KalfaEczaci/KalfaEczaciIslem
        public ActionResult Index()
        {
            var userId = Convert.ToInt32(User.Identity.GetUserId());
            var result = ctx.KalfaEczaci.Include("Kisi").Include("User").Include("User.Dosyalar").FirstOrDefault(x => x.UserId == userId);
            return View(result);
        }
        public JsonResult  Ekle(LoginEnt.KalfaEczaci dto)
        {
            if (!ModelState.IsValid)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest));
            }
            dto.UserId= Convert.ToInt32(User.Identity.GetUserId());
            try
            {
                string dosyaUrl = null;
                var file = Request.Files[0];
                if (file.ContentLength != 0)
                {
                     dosyaUrl = FileUploadHelper.LoadFile(null, Path.GetExtension(file.FileName), file.FileName.Substring(0, file.FileName.LastIndexOf(".")), Convert.ToInt32(User.Identity.GetUserId()), false, file, false);
                }
                var ent = ctx.KalfaEczaci.Include("User").Include("User.Dosyalar").FirstOrDefault(x=> x.Id==dto.Id);
                ctx.Entry(ent).CurrentValues.SetValues(dto);
                ctx.SaveChanges();
                return Json("Kayıt Başarılı");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
        public JsonResult Guncelle(LoginEnt.KalfaEczaci dto)
        {
            if (!ModelState.IsValid)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest));
            }
            try
            {
                string dosyaUrl = null;
                var file = Request.Files[0];
                if (file.ContentLength != 0)
                {
                    dosyaUrl = FileUploadHelper.LoadFile(null, Path.GetExtension(file.FileName), file.FileName.Substring(0, file.FileName.LastIndexOf(".")), Convert.ToInt32(User.Identity.GetUserId()), false, file, false);
                }
                dto.UserId = Convert.ToInt32(User.Identity.GetUserId());
                var ent = ctx.KalfaEczaci.Find(dto.Id);
                ctx.Entry(ent).CurrentValues.SetValues(dto);
                ctx.SaveChanges();
                return Json("Kayıt Başarılı");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }     
        public FileResult Download(int Id)
        {
            var dosya = ctx.Dosya.Find(Id);
            byte[] fileBytes = System.IO.File.ReadAllBytes(dosya.DosyaYolu);
            string fileName = Path.GetExtension(dosya.DosyaYolu);
            return File(fileBytes, "text/html", dosya.DosyaAdi+fileName);
        }
    }
}

Eczane.WebUI/Areas/User/Controllers/KisiBilgileriController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Http.Results;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Web.WebPages;
using Eczane.BL.Entities;
using Eczane.BL.Manage;
using Eczane.BL.Helpers;
using Microsoft.AspNet.Identity;

namespace Eczane.WebUI.Areas.User.Controllers
{
    [AllowAnonymous]
    public class KisiBilgileriController : Controller
    {
        private EczaneDbContext ctx;
        public KisiBilgileriController()
        {
            ctx=new EczaneDbContext();
        }
        // GET: User/KisiBilgileri
        public ActionResult Index()
        {          
            var id = Convert.ToInt32(User.Identity.GetUserId());
            var KisiBilgileri = ctx.User.Include("Kisi").FirstOrDefault(x => x.Id == id).Kisi;
            return View(KisiBilgileri);
        }
        [HttpPost]
        public JsonResult KisiBilgileriKaydet(LoginEnt.KisiBilgiler dto)
        {
            var userId = Convert.ToInt32(User.Identity.GetUserId());
            //if (!ModelState.IsValid)
            //{
            //    return Json("Model Geçerli Değil");
            //}
            string dosyaUrl = null;
            var file = Request.Files[0];
            try
            {
                if (ctx.User.Where(p=> p.Id== userId).Any(x=> x.Kisi!=null))
                {
                    return Json("Bu Kişinin Kullanıcı Bilgileri Eklidir O yüzden ekleme yapamazsınız!");
                }
                if (file.ContentLength != 0)
                {
                     dosyaUrl = FileUploadHelper.LoadFile(null, Path.GetExtension(file.FileName), file.FileName.Substring(0, file.FileName.LastIndexOf(".")), Convert.ToInt32(User.Identity.GetUserId()), false, file,true);
                }   
                dto.FotoUrl = dosyaUrl;
                var result = ctx.KisiBilgiler.Add(dto);
                ctx.SaveChanges();
                ctx.User.Include("Kisi").First(x => x.Id ==userId).KisiId= result.Id;
                var eczaci = ctx.Eczaci.FirstOrDefault(x => x.UserId == userId);
                if (eczaci != null)
                    eczaci.KisiId = result.Id;
                var KalfaEczaci = ctx.KalfaEczaci.FirstOrDefault(x => x.UserId == userId);
                if (KalfaEczaci != null)
                    KalfaEczaci.KisiId = result.Id;
                ctx.SaveChanges();
                return Json("Kayıt Başarılı");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
        [HttpPost]
        public JsonResult Guncelle(LoginEnt.KisiBilgiler dto)
        {
            var userId = Convert.ToInt32(User.Identity.GetUserId());
            if (!ModelState.IsValid)
            {
                return Json("Model Geçerli Değil");
            }
            var file = Request.Files[0];
            if (file.ContentLength!=0)
            {
                string pathToFiles = Server.MapPath("/");
                
                if (ctx.User.Include("Kisi").Any(x => x.Kisi.FotoUrl != null))
                {
                    var eskiFoto = ctx.User.Include("Kisi").FirstOrDefault(x => x.Id == userId).Kisi.FotoUrl;
                    if (eskiFoto!=null)
                    {
                        var dosyaYolu = ctx.Dosya.FirstOrDefault(c => c.DosyaUrl == eskiFoto).DosyaUrl.Remove(0, 1);
                        if (System.IO.File.Exists(@pathToFiles + dosyaYolu.Replace("/", "\\")))
                        {
                            System.IO.File.Delete(@pathToFiles + dosyaYolu.Replace("/", "\\"));
                        }
                    }
                }             
                var dosyaUrl = FileUploadHelper.LoadFile(null, Path.GetExtension(file.FileName), file.FileName.Substring(0, file.FileName.LastIndexOf(".")), Convert.ToInt32(User.Identity.GetUserId()), false, file, true);
                dto.FotoUrl = dosyaUrl;
            }
            try
            {                         
                var result = ctx.User.Include("Kisi").FirstOrDefault(x=> x.Id== userId && x.KisiId==dto.Id)?.Kisi;
                ctx.Entry(result).CurrentValues.SetValues(dto);
                ctx.SaveChanges();              
                return Json(dto);
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
    }
}

Eczane.WebUI/Areas/KalfaEczaci/Views/KalfaEczaciIslem/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage.cshtml";
}
@model Eczane.BL.Entities.LoginEnt.KalfaEczaci
<div class="row">
    <div class="col-md-6">
        <h1 class="page-header">
            Kalfa Eczaci <small>Kalfa Eczaci Bilgileri</small>
        </h1>
    </div>
    <div class="row" id="EkleForm" hidden="hidden" tabindex="1">
        <div class="col-md-12 panel panel-default">
            <div class="panel-heading">
                Rol Duzenleme
            </div>
            @*  <form role="form" class="panel panel-body" runat="Server"  enctype = "multipart/form-data" method="post" action="@Url.Action("KisiBilgileriKaydet","KisiBilgileri",new {area="User"})">    *@
            <form id="KisiBilgiileriForm" role="form" class="panel panel-body">
                @*<label>Id :</label>*@
                @Html.HiddenFor(m => m.Id)
                <div class="form-group">
                    <label class=""> Mezun Olduğu Fakilte Adi:</label>
                    @Html.TextBoxFor(m => m.MezunOlduguFakulteAdi, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Mezun Olduğu Tarih : </label>
                    @Html.TextBoxFor(m => m.MezunOlduguTarih, new { @class = "form-control datepicker",@data_format = "dd/MM/yyyy"  })
                </div>
                <div class="form-group">
                    <label>Foto Yukle</label>
                    <input type="file" runat="server" id="file" name="file" multiple="multiple">
                </div>
                <div style="text-align: right">
                    <button type="button" id="Kaydet" class="btn btn-primary ">Kaydet</button>
                    <button class="btn btn-success " id="Guncelle">Güncelle</button>
                    <button type="reset" class="btn btn-danger">Temizle</button>
                </div>
            </form>
        </div>
    </div>
    <div class="row" id="Form">
        <div class="col-md-12 panel panel-default">
            <div class="panel-heading">
                Kişi Bilgileri
            </div>
            <form role="form" class="panel panel-body">
                  
                <div class="col-md-9">
                    <div class="form-group">
                        <label>İsim :</label>
                        @Html.DisplayFor(m => m.Kisi.Ad)
                    </div>
                    <div class="form-group">
                        <label>Soy İsim : </label>
                        @Html.DisplayFor(m => m.Kisi.SoyAd)
                    </div>
                    <div class="form-group">
                        <label>Adres :</label>
                        @Html.DisplayFor(m => m.Kisi.Adres)
                    </div>
                    <div class="form-group ">
                        <label>MezunOlduğu FakulteAdi</label>
                        @Html.DisplayFor(m => m.MezunOlduguFakulteAdi)
                    </div>
                    <div class="form-group date">
                        <label>MezunOlduğu Tarih :</label>
                        @Html.DisplayFor(m => m.MezunOlduguTarih)
                    </div>
                    <div class="form-group">
                        <label>Sistem Puanı :</label>
                        @Html.DisplayFor(m => m.SistemPuan)
                    </div>
                </div>
                <div class="col-md-12">
                    <!-- Rol Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Dosyalar
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables">
                                    <thead>
                                    <tr>
                                        <th>Dosya Adı</th>
                                        <th style="text-align: center">işlem</th>
                                    </tr>
                                    </thead>
                                    <tbody id="bodytable">
                                    @if (Model==null)
                                    {
                                        <strong>Veri Yok</strong>
                                    }
                                    else
                                    {
                                        foreach (var obj in Model.User.Dosyalar)
                                        {
                                            <tr class="odd gradeX">
                                                <td>
                                                   @obj.DosyaAdi
                                                </td>
                                                <td style="text-align: center">
                                                    @Html.ActionLink("Download", "Download", new { Id=obj.Id})
                                                    @*<button onclick="Indir(@obj.Id)" type="button" class="btn btn-info">İndir</button>
                                                    <a href="@obj.DosyaYolu"> İndirlen</a>*@
                                                </td>
                                            </tr>
                                        }
                                    }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!--End Rol Tables -->
                </div>
                @*<div style="text-align: right">
                        <button type="button" id="FormGuncelle" class="btn btn-primary ">Guncelle</button>
                        <button type="reset" class="btn btn-danger">Temizle</button>
                    </div>*@
            </form>
        </div>
    </div>
    <div class="col-md-6" style="text-align: right">
        <button class="btn btn-primary" id="Ekle"><i class="fa fa-plus "></i>  Ekle</button>
        <button @*style="display: none"*@ class="btn btn-warning" id="Iptal"><i class="fa fa-plus "></i>  İptal</button>
    </div>
</div>
<div class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">Bilgi Mesajı</h4>
            </div>
            <div class="modal-body">
                <strong id="modalMesaj">

                </strong>
            </div>
            <div class="modal-footer">
                <button id="close" type="button" class="btn btn-default" data-dismiss="modal">Çıkış</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">İptal</button>
            </div>
        </div>
    </div>
</div>
<script>
    var sonuc;
    function Indir(Id) {
        console.log(Id);
        $.ajax({
            url: '@Url.Action("Download","KalfaEczaciIslem",new {Area="KalfaEczaci"})',
            type: 'POST',
            dataType: 'json',
            data: { Id: Id },
            success: function(data) {
                console.log(data);
            }
        });
    }
    $("#Ekle").on("click",
        function () {          
            $("#EkleForm").show();
            $('#EkleForm').focus();
        });
    $("#Iptal").on("click",
        function() {
            $("#EkleForm").hide();
        });
    $('.datepicker').datepicker({
        format: 'dd-mm-yyyy'
    });
    $("#Guncelle").on("click", function() {
        var form = $('form')[0];
        var fd = new FormData(form);       
        $.ajax({
            url: '@Url.Action("Guncelle","KalfaEczaciIslem",new {Area="KalfaEczaci"})',
            type: 'POST',
            dataType: 'json',
            contentType: false,
            processData: false,
            data: fd ,
            success: function (data) {
                $("#modalMesaj").text(data);
                $("#myModal").modal("show");
                sonuc = data;
                location.reload();
            }               
        });
    });
    $("#Kaydet").on('click',
        function () {
            var form = $('form')[0];
            var fd = new FormData(form);
            console.log(fd);
            $.ajax({
                url: '@Url.Action("Ekle","KalfaEczaciIslem",new {Area="KalfaEczaci"})',
                type: 'POST',
                dataType: 'json',
                contentType: false,
                processData: false,
                data: fd ,
                success: function (data) {
                    sonuc = data;
                    $("#modalMesaj").text(data);
                    $("#myModal").modal("show");
                }               
            });
        });
    $("#close").on("click",function() {
        if (sonuc = "Kayıt Başarılı") {
            location.reload();
        }
    });
</script>