Eczane.WebUI/Areas/Eczaci/Controllers/EczaciIslemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Http.Results;
using System.Web.Management;
using System.Web.Mvc;
using Eczane.BL.Entities;
using Eczane.BL.Manage;
using Eczane.WebApi.Models;
using Eczane.WebUI.Models;
using Microsoft.AspNet.Identity;

namespace Eczane.WebUI.Areas.Eczaci.Controllers
{
    public class EczaciIslemController : Controller
    {
        private readonly EczaneDbContext ctx;
        public EczaciIslemController()
        {
            ctx=new EczaneDbContext();
        }
        public ActionResult EczaciIndex()
        {
            var result = ctx.KalfaEczaci.Include("Kisi").OrderBy(x=> x.SistemPuan).Take(10).Select(x=> new KalfaDTO()
            {
                Kisi = x.Kisi,MezunOlduguFakulteAdi = x.MezunOlduguFakulteAdi,
                MezunOlduguTarih = x.MezunOlduguTarih,
                Id = x.Id
            }).ToList();
            return View(result);
        }
        // GET: Eczaci/EczaciIslem
        public ActionResult Index()
        {
            //LoginEnt.KalfaEczaci result=null;
            //var client = new HttpClient();
            //client.BaseAddress = new Uri("http://localhost:57939/");
            //client.DefaultRequestHeaders.Accept.Clear();
            //client.DefaultRequestHeaders.TryAddWithoutValidation("Authorization", "");
            //client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            //var response =  client.GetAsync("api/KalfaEczacilar/Search").Result;
            //if (response.IsSuccessStatusCode)
            //{
            //    result = response.Content.ReadAsAsync<LoginEnt.KalfaEczaci>().Result;
            //}
            var result = ctx.KalfaEczaci.Include("User").Include("Kisi").ToList();
            return View(result);
        }
        public ActionResult EczaciBilgileri()
        {
            if (ctx.Eczaci.Count() != 0)
            {
                var userId = Convert.ToInt32(User.Identity.GetUserId());
                var result = ctx.Eczaci.Include("Kisi")
                    .FirstOrDefault(x => x.UserId == userId);
                return View(result);
            }
            return View();
        }
        [HttpPost]
        public ActionResult EczaciBilgileri(LoginEnt.Eczaci dto)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest) ;
            }
            var userId = Convert.ToInt32(User.Identity.GetUserId());
            dto.UserId = userId;
             ctx.Entry(ctx.Eczaci.Where(x => x.UserId == userId).First()).CurrentValues
                .SetValues(dto);
            ctx.SaveChanges();
            return View();
        }
        public JsonResult GuncelleEczaciBilgileri(LoginEnt.Eczaci dto)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json("Veriler Hatalı");
                }
                var userId = Convert.ToInt32(User.Identity.GetUserId());
                dto.UserId = userId;
                var result = ctx.Eczaci.FirstOrDefault(x=> x.Id==dto.Id);
                ctx.Entry(result).CurrentValues.SetValues(dto);
                ctx.SaveChanges();
                return Json("Guncelleme Başarılı");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
        public JsonResult GetKalfaBilgileri(int Id)
        {
            try
            {
                var result=ctx.KalfaEczaci.Include("Kisi").Include("User.Dosyalar").FirstOrDefault(x=> x.Id==Id);
                EczaciKalfaAramaDTO dto= new EczaciKalfaAramaDTO();
                dto.Kisi = result.Kisi;
                dto.Dosyalar = result.User.Dosyalar;
                foreach (var item in dto.Dosyalar)
                {
                    item.User = null;
                }
                dto.Kalfa = result;
                dto.Kalfa.User = null;
                return Json(dto, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
        public JsonResult IstekYap(int kalfaId)
        {
            try
            {
                var userId = Convert.ToInt32(User.Identity.GetUserId());
                var eczId = ctx.Eczaci.FirstOrDefault(x=> x.UserId==userId).Id;
                LoginEnt.IstekBilgileri istek= new LoginEnt.IstekBilgileri()
                {
                    AdminIstekOnayTarihi = null,
                    EczId = eczId,
                    KalfaId = kalfaId,
                    IstekGonderilmeTarihi = DateTime.Now 
                };
                ctx.IstekBilgileri.Add(istek);
                ctx.SaveChanges();
                return Json("İstek Yapıldı.",JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
        public ActionResult KalfaBigileri(int id)
        {
            var result = ctx.KalfaEczaci.Include("User").Include("Kisi").Include("Dosya").Select(x=> new KalfaDTO()
            {
                Kisi = x.Kisi,
                Dosyalar = x.User.Dosyalar,
                MezunOlduguFakulteAdi = x.MezunOlduguFakulteAdi,
                MezunOlduguTarih = x.MezunOlduguTarih,
                SistemPuan = x.SistemPuan,
                Id = x.Id
            }).FirstOrDefault();
            return View(result);
        }
    }
}

Eczane.WebUI/Areas/KalfaEczaci/Controllers/KalfaEczaciIslemController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Eczane.BL.Entities;
using Eczane.BL.Helpers;
using Eczane.BL.Manage;
using Microsoft.AspNet.Identity;

namespace Eczane.WebUI.Areas.KalfaEczaci.Controllers
{
    public class KalfaEczaciIslemController : Controller
    {
        private readonly EczaneDbContext ctx;
        public KalfaEczaciIslemController()
        {
            ctx=new EczaneDbContext();
        }
        // GET: KalfaEczaci/KalfaEczaciIslem
        public ActionResult Index()
        {
            var userId = Convert.ToInt32(User.Identity.GetUserId());
            var result = ctx.KalfaEczaci.Include("Kisi").Include("User").Include("User.Dosyalar").FirstOrDefault(x => x.UserId == userId);
            return View(result);
        }
        public JsonResult  Ekle(LoginEnt.KalfaEczaci dto)
        {
            if (!ModelState.IsValid)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest));
            }
            dto.UserId= Convert.ToInt32(User.Identity.GetUserId());
            try
            {
                string dosyaUrl = null;
                var file = Request.Files[0];
                if (file.ContentLength != 0)
                {
                     dosyaUrl = FileUploadHelper.LoadFile(null, Path.GetExtension(file.FileName), file.FileName.Substring(0, file.FileName.LastIndexOf(".")), Convert.ToInt32(User.Identity.GetUserId()), false, file, false);
                }
                var ent = ctx.KalfaEczaci.Include("User").Include("User.Dosyalar").FirstOrDefault(x=> x.Id==dto.Id);
                ctx.Entry(ent).CurrentValues.SetValues(dto);
                ctx.SaveChanges();
                return Json("Kayıt Başarılı");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
        public JsonResult Guncelle(LoginEnt.KalfaEczaci dto)
        {
            if (!ModelState.IsValid)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest));
            }
            try
            {
                string dosyaUrl = null;
                var file = Request.Files[0];
                if (file.ContentLength != 0)
                {
                    dosyaUrl = FileUploadHelper.LoadFile(null, Path.GetExtension(file.FileName), file.FileName.Substring(0, file.FileName.LastIndexOf(".")), Convert.ToInt32(User.Identity.GetUserId()), false, file, false);
                }
                dto.UserId = Convert.ToInt32(User.Identity.GetUserId());
                var ent = ctx.KalfaEczaci.Find(dto.Id);
                ctx.Entry(ent).CurrentValues.SetValues(dto);
                ctx.SaveChanges();
                return Json("Kayıt Başarılı");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }     
        public FileResult Download(int Id)
        {
            var dosya = ctx.Dosya.Find(Id);
            byte[] fileBytes = System.IO.File.ReadAllBytes(dosya.DosyaYolu);
            string fileName = Path.GetExtension(dosya.DosyaYolu);
            return File(fileBytes, "text/html", dosya.DosyaAdi+fileName);
        }
    }
}

Eczane.WebUI/Areas/User/Controllers/KisiBilgileriController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Http.Results;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Web.WebPages;
using Eczane.BL.Entities;
using Eczane.BL.Manage;
using Eczane.BL.Helpers;
using Microsoft.AspNet.Identity;

namespace Eczane.WebUI.Areas.User.Controllers
{
    [AllowAnonymous]
    public class KisiBilgileriController : Controller
    {
        private EczaneDbContext ctx;
        public KisiBilgileriController()
        {
            ctx=new EczaneDbContext();
        }
        // GET: User/KisiBilgileri
        public ActionResult Index()
        {          
            var id = Convert.ToInt32(User.Identity.GetUserId());
            var KisiBilgileri = ctx.User.Include("Kisi").FirstOrDefault(x => x.Id == id).Kisi;
            return View(KisiBilgileri);
        }
        [HttpPost]
        public JsonResult KisiBilgileriKaydet(LoginEnt.KisiBilgiler dto)
        {
            var userId = Convert.ToInt32(User.Identity.GetUserId());
            //if (!ModelState.IsValid)
            //{
            //    return Json("Model Geçerli Değil");
            //}
            string dosyaUrl = null;
            var file = Request.Files[0];
            try
            {
                if (ctx.User.Where(p=> p.Id== userId).Any(x=> x.Kisi!=null))
                {
                    return Json("Bu Kişinin Kullanıcı Bilgileri Eklidir O yüzden ekleme yapamazsınız!");
                }
                if (file.ContentLength != 0)
                {
                     dosyaUrl = FileUploadHelper.LoadFile(null, Path.GetExtension(file.FileName), file.FileName.Substring(0, file.FileName.LastIndexOf(".")), Convert.ToInt32(User.Identity.GetUserId()), false, file,true);
                }   
                dto.FotoUrl = dosyaUrl;
                var result = ctx.KisiBilgiler.Add(dto);
                ctx.SaveChanges();
                ctx.User.Include("Kisi").First(x => x.Id ==userId).KisiId= result.Id;
                var eczaci = ctx.Eczaci.FirstOrDefault(x => x.UserId == userId);
                if (eczaci != null)
                    eczaci.KisiId = result.Id;
                var KalfaEczaci = ctx.KalfaEczaci.FirstOrDefault(x => x.UserId == userId);
                if (KalfaEczaci != null)
                    KalfaEczaci.KisiId = result.Id;
                ctx.SaveChanges();
                return Json("Kayıt Başarılı");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
        [HttpPost]
        public JsonResult Guncelle(LoginEnt.KisiBilgiler dto)
        {
            var userId = Convert.ToInt32(User.Identity.GetUserId());
            if (!ModelState.IsValid)
            {
                return Json("Model Geçerli Değil");
            }
            var file = Request.Files[0];
            if (file.ContentLength!=0)
            {
                string pathToFiles = Server.MapPath("/");
                
                if (ctx.User.Include("Kisi").Any(x => x.Kisi.FotoUrl != null))
                {
                    var eskiFoto = ctx.User.Include("Kisi").FirstOrDefault(x => x.Id == userId).Kisi.FotoUrl;
                    if (eskiFoto!=null)
                    {
                        var dosyaYolu = ctx.Dosya.FirstOrDefault(c => c.DosyaUrl == eskiFoto).DosyaUrl.Remove(0, 1);
                        if (System.IO.File.Exists(@pathToFiles + dosyaYolu.Replace("/", "\\")))
                        {
                            System.IO.File.Delete(@pathToFiles + dosyaYolu.Replace("/", "\\"));
                        }
                    }
                }             
                var dosyaUrl = FileUploadHelper.LoadFile(null, Path.GetExtension(file.FileName), file.FileName.Substring(0, file.FileName.LastIndexOf(".")), Convert.ToInt32(User.Identity.GetUserId()), false, file, true);
                dto.FotoUrl = dosyaUrl;
            }
            try
            {                         
                var result = ctx.User.Include("Kisi").FirstOrDefault(x=> x.Id== userId && x.KisiId==dto.Id)?.Kisi;
                ctx.Entry(result).CurrentValues.SetValues(dto);
                ctx.SaveChanges();              
                return Json(dto);
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
    }
}

Eczane.WebUI/Areas/Eczaci/Views/EczaciIslem/EczaciBilgileri.cshtml
@{
    ViewBag.Title = "EczaciBilgileri";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage.cshtml";
}
@model Eczane.BL.Entities.LoginEnt.Eczaci
<div class="row">
    <div class="col-md-6">
        <h1 class="page-header">
            Bilgiler <small>Kişisel Bilgiler</small>
        </h1>
    </div>
    <div class="col-md-6" style="text-align: right">
        <button class="btn btn-primary" id="Ekle"><i class="fa fa-plus "></i>  Ekle</button>
        <button @*style="display: none"*@ class="btn btn-warning" id="Iptal"><i class="fa fa-plus "></i>  İptal</button>
    </div>
</div>
<div class="row" id="KisiBilgileriEkleForm" hidden="hidden">
    <div class="col-md-12 panel panel-default">
        <div class="panel-heading">
            Rol Duzenleme
        </div>
        @*  <form role="form" class="panel panel-body" runat="Server"  enctype = "multipart/form-data" method="post" action="@Url.Action("KisiBilgileriKaydet","KisiBilgileri",new {area="User"})">    *@
        <form id="EczaciBilgiileriForm" role="form" class="panel panel-body">        
            @*<label>Id :</label>*@
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <label class="">GIN Numarası :</label>
                @Html.TextBoxFor(m => m.GIN_Numarasi, new {@class = "form-control"})
            </div>
                  
            @*<div class="form-group">
                <label>Foto Yukle</label>
                <input type="file" runat="server" id="file" name="file" multiple="multiple">
            </div>*@
            <div style="text-align: right">
                <button type="button" id="Kaydet" class="btn btn-primary ">Kaydet</button>
                <button class="btn btn-success " type="button" id="Guncelle">Güncelle</button>
                <button type="reset" class="btn btn-danger">Temizle</button>
            </div>
        </form>
    </div>
</div>
<div class="row" id="EczaciBilgileri" >
    <div class="col-md-12 panel panel-default">
        <div class="panel-heading">
            Kişi Bilgileri
        </div>
        <form role="form" class="panel panel-body">
            <div class="col-md-9">               
                <div class="form-group">
                    <label>İsim :</label>
                    @Html.DisplayFor(m => m.User.Kisi.Ad)
                </div>
                <div class="form-group">
                    <label>Soy İsim :</label>
                    @Html.DisplayFor(m => m.User.Kisi.SoyAd)
                </div>
                <div class="form-group">
                    <label>GIN_Numarasi :</label>
                    @Html.DisplayFor(m => m.GIN_Numarasi)
                </div>
                <div class="form-group">
                    <label>Kalfa Eczacı İsteleri :</label>
                   
                </div>            
            </div>
        </form>
    </div>
</div>
<script>
    $("#Ekle").on("click", function() {
        $("#KisiBilgileriEkleForm").show();
    });
    $("#Iptal").on("click", function() {
        $("#KisiBilgileriEkleForm").hide();
    });
    $("#Guncelle").on("click", function() {
        var form = $('form')[0];
        var fd = new FormData(form);       
        $.ajax({
            url: '@Url.Action("GuncelleEczaciBilgileri","EczaciIslem",new {Area="Eczaci"})',
            type: 'POST',
            dataType: 'json',
            contentType: false,
            processData: false,
            data: fd ,
            success: function (data) {
                console.log(data);
                location.reload();
            }               
        });
    });
    $("#Kaydet").on('click',
        function () {
            var form = $('form')[0];
            var fd = new FormData(form);       
            $.ajax({
                url: '@Url.Action("EczaciBilgileri","EczaciIslem",new {Area="Eczaci"})',
                type: 'POST',
                dataType: 'json',
                contentType: false,
                processData: false,
                data: fd ,
                success: function (data) {
                    location.reload();
                    console.log(data);
                }               
            });
        });
</script>

Eczane.WebUI/Areas/Eczaci/Views/EczaciIslem/EczaciIndex.cshtml
@{
    ViewBag.Title = "EczaciIndex";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage.cshtml";
}
@model List<Eczane.WebApi.Models.KalfaDTO>
<div class="row">
    <div class="col-md-6">
        <h1 class="page-header">
            Eczaci <small>Kalfa Eczaci Arama </small>
        </h1>
    </div>
</div>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-3 col-sm-12 col-xs-12" onclick='@Url.Action("KalfaBigileri","EczaciIslem",new{id=@item.Id})' id=@item.Id>
            <div class="panel panel-primary text-center no-boder">
                <div class="panel-body">
                    <img src=@item.Kisi.FotoUrl />
                    <h3>@item.Kisi.Ad  @item.Kisi.SoyAd</h3>
                </div>
                <div class="panel-footer">
                 Puanı    @item.SistemPuan
                </div>
            </div>
        </div>
    }
</div>
<script>
    
</script>

Eczane.WebUI/Areas/Eczaci/Views/EczaciIslem/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage.cshtml";
}
@model List<Eczane.BL.Entities.LoginEnt.KalfaEczaci>
<div class="row">
    <div class="col-md-6">
        <h1 class="page-header">
            Eczaci <small>Kalfa Eczaci Arama </small>
        </h1>
    </div>
    <div class="col-md-6" style="text-align: right">
        <button class="btn btn-primary" id="Ekle"><i class="fa fa-plus "></i>  Ara</button>
        <button @*style="display: none"*@ class="btn btn-warning" id="Temizle"><i class="fa fa-plus "></i>  Temizle</button>
    </div>
    <div class="row col-md-12">
        <div class="panel-body">
            <div class="table-responsive">
                <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" aria-describedby="dataTables-example_info">
                        <thead>
                        <tr role="row">
                            <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Adı</th>
                            <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">SoyAdı</th>
                            <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">İl</th>
                            <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">İlçe</th>
                            <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Bilgiler</th>
                            <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">İstek İşlemi</th>
                        </tr>
                        </thead>
                        <tbody>                       
                        @foreach (var item in Model)
                        {
                            if (item.Kisi==null)
                            {
                               
                            }
                            else
                            {
                                <tr>
                                    <td>@item.Kisi.Ad</td>
                                    <td>@item.Kisi.SoyAd</td>
                                    <td>@item.Kisi.IlId</td>
                                    <td>@item.Kisi.IlceId</td>
                                    <td onclick="Bilgi(@item.Id)"><i class="fa fa-info"></i> Bilgi</td>
                                    <td><i class="fa fa-info" onclick="IstekYap(@item.Id)"></i></td>
                                </tr>
                            }
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">Kalfa Bilgisi</h4>
            </div>
            <div class="modal-body">
                <strong id="modalMesaj">
                </strong>
                <div class="col-md-12">
                    <div class="form-group">
                        <label>İsim :</label>
                        @Html.TextBox("Ad","",new {@style= "margin-left: 5%;" })
                    </div>
                    <div class="form-group">
                        <label>Soy İsim : </label>
                        @Html.TextBox("SoyAd","", new { @style = "margin-left: 0%;" })
                    </div>
                    <div class="form-group">
                        <label>Adres :</label>
                        @Html.TextBox("Adres", "",new { @style = "margin-left: 3%;" })
                    </div>
                    <div class="form-group">
                        <label>Mezun Oldugu Fakulte Adi :</label>
                        @Html.TextBox("MezunOlduguFakulteAdi","", new { @style = "margin-left: 5%;" })
                    </div>
                    <div class="form-group">
                        <label>Mezun Oldugu Tarih :</label>
                        @Html.TextBox("MezunOlduguTarih","", new { @style = "margin-left: 12%;" })
                    </div>
                    <div class="form-group">
                        <label>Sistem Puanı</label>
                        @Html.TextBox("SistemPuan", "",new { @style = "margin-left: 22%;" })
                    </div>                 
                    <div class="form-group">
                        <label>Dosyalar</label>
                        <div class="row col-md-12 form-group">
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <div id="DosyaTable" class="dataTables_wrapper form-inline" role="grid">
                                        <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" aria-describedby="dataTables-example_info">
                                            <thead>
                                            <tr role="row">
                                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Dosya Adı</th>
                                                <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 163px;">Dosya İndir</th>
                                            </tr>
                                            </thead>
                                            <tbody>                       
                                                    
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade in" id="myModalMesaj" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabelMesaj">Bilgi Mesajı</h4>
            </div>
            <div class="modal-body">
                <strong id="modalMesajMesaj">

                </strong>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<script>
    function IstekYap(kalfaId) {
        $.ajax({
            url: '@Url.Action("IstekYap","EczaciIslem",new {Area="Eczaci"})',
            data: { kalfaId: kalfaId},
            success: function (data) {
                $("#modalMesmodalMesajMesajajMesaj").text(data);
                $("#myMmyModalMesajodal").modal("show");
            },
            type: 'GET',
            dataType: 'json'
        });
    }
    function Bilgi(id) {
        $.ajax({
            url: '@Url.Action("GetKalfaBilgileri","EczaciIslem",new {Area="Eczaci"})',
            data: { Id: id },
            success: function (data) {
                console.log(data);
                console.log(data.Kisi);
                $("#myModal").modal("show");
                $("#Ad").val(data.Kisi.Ad);
                $("#SoyAd").val(data.Kisi.SoyAd);
                $("#SistemPuan").val(data.Kalfa.SistemPuan);
                $("#MezunOlduguTarih").val(data.Kalfa.MezunOlduguTarih);
                $("#MezunOlduguFakulteAdi").val(data.Kalfa.MezunOlduguFakulteAdi);
                $("#Adres").val(data.Kisi.Adres);
                $.each(data.Dosyalar,
                    function(i, item) {
                        $("#DosyaTable tbody").append(
                            "<tr>" +
                            "<td>" +
                            item.DosyaAdi +
                            "</td>" +
                            "<td>" + "<a href=/KalfaEczaci/KalfaEczaciIslem/Download/" + item.Id +">İndir</a>"+
                           "</td>" +
                            "</tr>"
                        );
                    });
            },
            type: 'GET',
            dataType: 'json'
        });
    }
    $(document).ready(function () {
        $('#dataTables-example').dataTable();
    });
</script>