Eczane.WebUI/Areas/Admin/Controllers/Rol_IslemController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Web;
using System.Web.Configuration;
using System.Web.Hosting;
using System.Web.Http.Results;
using System.Web.Mvc;
using Eczane.BL.Entities;
using Eczane.BL.Manage;

namespace Eczane.WebUI.Areas.Admin.Controllers
{
    public class Rol_IslemController : Controller
    {
        private EczaneDbContext ctx;
        public Rol_IslemController()
        {
            ctx = new EczaneDbContext();
        }
        // GET: Admin/Rol_Islem
        public ActionResult Index()
        {
            return View(ctx.Role.AsNoTracking().ToList());
        }
        public JsonResult GetAllRole()
        {
            return Json(ctx.Role.ToList(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult RoleEkle(LoginEnt.Role dto)
        {
            if (!ModelState.IsValid || (string.IsNullOrEmpty(dto.Name) || string.IsNullOrWhiteSpace(dto.Name)))
                return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Data is not invalid"));
            try
            {
                var result = ctx.Role.Add(dto);
                ctx.SaveChanges();
                return Json(new HttpStatusCodeResult(HttpStatusCode.OK, "Adding Data is successful"));
            }
            catch (Exception e)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.ExpectationFailed, e.Message));
            }
        }
        public JsonResult RolDuzenle(LoginEnt.Role dto)
        {
            if (!ModelState.IsValid || (string.IsNullOrEmpty(dto.Name) || string.IsNullOrWhiteSpace(dto.Name)))
                return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Data is not invalid"));
            try
            {
                var data = ctx.Role.Find(dto.Id);
                ctx.Entry(data).CurrentValues.SetValues(dto);
                //ctx.SaveChanges();
                return Json(new HttpStatusCodeResult(HttpStatusCode.OK, "Updating Data is successful"));
            }
            catch (Exception e)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.ExpectationFailed, e.Message));
            }
        }
        public JsonResult GetRole(int Id)
        {
            if (!ModelState.IsValid || Id == null || Id == 0)
                return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Data is not invalid"));
            try
            {
                var result = ctx.Role.Find(Id);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.ExpectationFailed, e.Message));
            }
        }
        public JsonResult DeleteRole(int id)
        {
            if (!ModelState.IsValid || id == null || id == 0)
                return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Data is not invalid"));
            try
            {
                var result = ctx.Role.Find(id);
                ctx.Role.Remove(result);
                ctx.SaveChanges();
                return Json("Veri silindi", JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.ExpectationFailed, e.Message));
            }
        }
        public ActionResult KullaniciyaRolAta()
        {
            IDictionary<int, string> veriler = new Dictionary<int, string>();
            try
            {
                var kullanicilar = ctx.User.Include("Kisi").Where(x=> x.KisiId!=null).ToList();
                ViewData["Kullanicilar"] = kullanicilar;
                ViewData["Roller"] =
                    ctx.Role.ToList();          
                return View();
            }
            catch (Exception e)
            {
                throw;
            }
        }
        public JsonResult KullaniciyaRoleAtaKaydet(int userId,int roleId)
        {
            if (!ModelState.IsValid)
            {
                return Json("Model Hatalı");
            }
            try
            {
                var user = ctx.User.Find(userId);
                var role = ctx.Role.Find(roleId);
                var userRole=new LoginEnt.UserRole()
                {
                    RoleId = roleId,
                    UserId = userId
                };
                ctx.UserRole.Add(userRole);
                ctx.SaveChanges();
                return Json("Kayıt Başarılı",JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
        public ActionResult RolYetkiAtama()
        {
            return View();
        }
    }
}

Eczane.WebUI/Areas/Admin/Views/Rol_Islem/Index.cshtml
@using Eczane.BL.Entities
@model List<Eczane.BL.Entities.LoginEnt.Role>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage.cshtml";
}
@*<link href="~/assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />*@
@*<script src="~/assets/js/jquery.metisMenu.js"></script>*@
<!-- Morris Chart Js -->
@*<script src="~/assets/js/morris/raphael-2.1.0.min.js"></script>
<script src="~/assets/js/morris/morris.js"></script>*@
<div class="row">
    <div class="col-md-6">
        <h1 class="page-header">
            Rol isimleri <small>Roller</small>
        </h1>
    </div>
    <div class="col-md-6" style="text-align: right">
        <button class="btn btn-primary" id="Ekle"><i class="fa fa-plus "></i>  Ekle</button>
        <button style="display: none" class="btn btn-warning" id="Iptal"><i class="fa fa-plus "></i>  İptal</button>
    </div>
</div>
<div class="row" id="duzenlemeForm" hidden="hidden">
    <div class="col-md-12 panel panel-default">
        <div class="panel-heading">
            Rol Duzenleme
        </div>
        <form role="form" class="panel panel-body">
            <div class="form-group">
                <label>Rol Id</label>
                <input id="roleId" class="form-control" readonly="readonly">
            </div>
            <div class="form-group">
                <label>Rol Ad</label>
                @Html.ValidationMessage("Data is not invalid")
                <input id="roleAd" class="form-control">
            </div>
            <div style="text-align: right">
                <button type="button" id="FormGuncelle" class="btn btn-primary ">Guncelle</button>
                <button type="reset" class="btn btn-danger">Temizle</button>
            </div>
        </form>
    </div>
</div>
<div class="row" id="EkleDiv" hidden="hidden">
    <div class="col-md-12 panel panel-default">
        <div class="panel-heading">
            Rol Ekleme
        </div>
        <form role="form" class="panel panel-body">
            <div class="form-group">
                <label>Rol Ad</label>
                <input id="Name" class="form-control" placeholder="Role adını giriniz">
            </div>
            <div style="text-align: right">
                <button type="button" id="RolEkleBtn" class="btn btn-primary ">Kaydet</button>
                <button type="reset" class="btn btn-danger">Temizle</button>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <!-- Rol Tables -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Rol Tablosu
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th style="text-align: center">işlem</th>
                            </tr>
                        </thead>
                        <tbody id="bodytable">
                            @if (Model.Count == 0)
                            {
                                <strong>Veri Yok</strong>
                            }
                            else
                            {
                                foreach (var obj in Model)
                                {
                                    <tr class="odd gradeX">
                                        <td>
                                            @obj.Id
                                        </td>
                                        <td>
                                            @obj.Name
                                        </td>
                                        <td style="text-align: center">
                                            <button onclick="Duzenle(@obj.Id)" type="submit" class="btn btn-primary">Güncelle</button>
                                            <button onclick="Sil(@obj.Id)" type="submit" class="btn btn-info">Sil</button>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!--End Rol Tables -->
    </div>
</div>   
<script>
    $("#Ekle").on("click", function () {
        $("#EkleDiv").show();
        $("#Iptal").show();
    });
    $("#Iptal").on("click",
        function() {
            $("#EkleDiv").hide();
            $("#duzenlemeForm").hide();
            $("#Iptal").hide();
        });
    function Duzenle(id) {
        console.log(id);
        $("#duzenlemeForm").show();
        $("#Iptal").show();
        $.ajax({
            url: '@Url.Action("GetRole","Rol_Islem",new {Area="Admin"})',
            data: { Id: id },
            success: function (data) {
                console.log(data);
                $('#roleId').val(data.Id);
                $('#roleAd').val(data.Name);
            },
            type: 'GET',
            dataType: 'json'
        });
    }
        $("#RolEkleBtn").on("click",function () {
                var dto = {};
                //dto.Id = $("#roleId").val();
                dto.Name = $("#Name").val();
                $.ajax({
                    url: '@Url.Action("RoleEkle","Rol_Islem",new {Area="Admin"})',
                    data: dto,
                    success: function (data) {
                        console.log(data);
                        $.ajax({
                            url: '@Url.Action("GetAllRole","Rol_Islem",new {Area="Admin"})',
                            success: function (data) {
                                GetData();
                            },
                            type: 'GET',
                            dataType: 'json'
                        });
                    },
                    type: 'POST',
                    dataType: 'json'
                });
            });
        $("#FormGuncelle").on("click",
                function () {
                    var dto = {};
                    dto.Id = $("#roleId").val();
                    $.ajax({
                        url: '@Url.Action("RolDuzenle","Rol_Islem",new {Area="Admin"})',
                        data: dto,
                        success: function (data) {
                            console.log(data);
                            GetData();
                        },
                        type: 'POST',
                        dataType: 'json'
                    });
                });
    function Sil(id) {
        $.ajax({
            url: '@Url.Action("DeleteRole","Rol_Islem",new {Area="Admin"})',
            data: {id:id},
            success: function (data) {
                GetData();
                console.log(data);
            },
            type: 'GET',
            dataType: 'json'
        });
        }
    function GetData() {
        $.ajax({
            url: '@Url.Action("GetAllRole","Rol_Islem",new {Area="Admin"})',
            success: function (data) {
                var table = $('#dataTables').DataTable();
                table.destroy();
                $("#bodytable").html("");
                $.each(data,
                    function(key, value) {
                        $("#bodytable").append("<tr><td class='text-center'>" +
                            value.Id +
                            "</td>" +
                            "<td>" +
                            value.Name +
                            "</td>" +
                            "<td style='text-align: center'><button onclick='Duzenle(" +
                            value.Id +
                            ")' type='submit' class='btn btn-primary'>Güncelle</button><button onclick='Sil(" +
                            value.Id +
                            ")' type='submit' class='btn btn-info'>Sil</button></td>");
                    });
            }
                });
    }
</script>

Eczane.WebUI/Areas/Admin/Views/Rol_Islem/KullaniciyaRolAta.cshtml
@using Eczane.BL.Entities

@{
    ViewBag.Title = "KullaniciyaRolAta";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage.cshtml";
}
<link href="~/assets/js/select2-4.0.4/dist/css/select2.min.css" rel="stylesheet" />
<script src="~/assets/js/select2-4.0.4/dist/js/select2.js"></script>
<script src="~/assets/js/select2-4.0.4/dist/js/select2.min.js"></script>
<div class="row">
    <div class="col-md-6">
        <select style="width: 100%" class="" id="KullaniciAdi" name="state">
            @{
                var kisi = ViewData["Kullanicilar"] as List<LoginEnt.User>;
                if (kisi.Count == 0)
                {
                    <option>Kisiler Yok..........</option>
                }
                else
                {
                    <option value=0>İsim Seçiniz</option>
                    foreach (var item in @ViewData["Kullanicilar"] as List<LoginEnt.User>)
                    {
                        <option value="@item.Id">@item.Kisi.Ad</option>
                    }
                }
            }
        </select>
    </div>
    <div class="col-md-6">
        <select style="width: 100%" class="" id="Rol" name="state">
            <option value="0" selected="selected">Rol Seçiniz</option>
            @foreach (var item in @ViewData["Roller"] as List<LoginEnt.Role>)
            {
                <option value="@item.Id">@item.Name</option>
            }
        </select>
    </div>
</div>
<div class="clearfix"></div>
<div class="row" style="margin-top: 2%">
    <div class="col-md-12">
        <div style="text-align: center">
            <button type="button" id="Kaydet" class="btn btn-primary ">Kaydet</button>
            <button type="reset" class="btn btn-danger">Temizle</button>
        </div>
    </div>
</div>
<div class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">Bilgi Mesajı</h4>
            </div>
            <div class="modal-body">
                <strong id="modalMesaj">

                </strong>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('select').select2();
    });
    $("#Kaydet").on("click",
        function() {
            $.ajax({
                url: '@Url.Action("KullaniciyaRoleAtaKaydet","Rol_Islem",new {Area="Admin"})',
                data: {
                    userId: $("#KullaniciAdi").val(),
                    roleId: $("#Rol").val()
                },
                success: function (data) {
                    $("#modalMesaj").text(data);
                    $("#myModal").modal("show");
                    $("#KullaniciAdi").val(0).change();
                    $("#Rol").val(0).change();
                },
                type: 'GET',
                dataType: 'json'
            });
        });
</script>

Eczane.WebUI/Areas/Admin/Views/Rol_Islem/RolYetkiAtama.cshtml
@{
    ViewBag.Title = "RolYetkiAtama";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage.cshtml";
}
<div class="row">
    <div class="col-md-6">
        <h1 class="page-header">
            Rol İşlemleri <small>Role Yetki Atama</small>
        </h1>
    </div>
    <div class="col-md-6" style="text-align: right">
        <button class="btn btn-primary" id="Ekle"><i class="fa fa-plus "></i>  Ekle</button>
        <button style="display: none" class="btn btn-warning" id="Iptal"><i class="fa fa-plus "></i>  İptal</button>
    </div>
</div>
<div class="row" id="duzenlemeForm" hidden="hidden">
    <div class="col-md-12 panel panel-default">
        <div class="panel-heading">
            Rol Duzenleme
        </div>
        <form role="form" class="panel panel-body">
            <div class="form-group">
                <label>Rol Id</label>
                <input id="roleId" class="form-control" readonly="readonly">
            </div>
            <div class="form-group">
                <label>Rol Ad</label>
                @Html.ValidationMessage("Data is not invalid")
                <input id="roleAd" class="form-control">
            </div>
            <div style="text-align: right">
                <button type="button" id="FormGuncelle" class="btn btn-primary ">Guncelle</button>
                <button type="reset" class="btn btn-danger">Temizle</button>
            </div>
        </form>
    </div>
</div>